"""
PDF Generation Router — Deep Research → PDF export.

Endpoints:
  POST /pdf/generate       — Generate a PDF from markdown/HTML content
  POST /pdf/research       — Run deep research via AI, then render as PDF
  GET  /pdf/file/{filename} — Serve a generated PDF

Uses weasyprint (preferred) or fpdf2 as fallback.
"""
from __future__ import annotations

import hashlib
import html as _html
import logging
import os
import tempfile
import time
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel

logger = logging.getLogger("pdf_router")
router = APIRouter(prefix="/pdf", tags=["pdf"])

PDF_DIR = Path(tempfile.gettempdir()) / "pai_pdfs"
PDF_DIR.mkdir(exist_ok=True)


class PdfGenerateRequest(BaseModel):
    title: str = "Document"
    content: str  # Markdown or HTML
    format: str = "markdown"  # "markdown" | "html"


class PdfResearchRequest(BaseModel):
    topic: str
    depth: str = "standard"  # "brief" | "standard" | "deep"
    pages: int = 5  # approximate target pages


def _markdown_to_html(md_text: str, title: str = "Document") -> str:
    """Convert markdown to styled HTML for PDF rendering."""
    try:
        import markdown
        body = markdown.markdown(
            md_text,
            extensions=["tables", "fenced_code", "codehilite", "toc", "nl2br"]
        )
    except ImportError:
        # Minimal fallback: wrap in <pre> if markdown lib not installed
        body = f"<pre style='white-space:pre-wrap;font-family:sans-serif'>{md_text}</pre>"

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  @page {{ margin: 2.5cm; size: A4; }}
  body {{
    font-family: -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif;
    font-size: 11pt; line-height: 1.7; color: #1d1d1f;
    max-width: 100%;
  }}
  h1 {{ font-size: 22pt; font-weight: 700; color: #0071e3; margin-top: 0; border-bottom: 2px solid #0071e3; padding-bottom: 8px; }}
  h2 {{ font-size: 16pt; font-weight: 600; color: #1d1d1f; margin-top: 28px; }}
  h3 {{ font-size: 13pt; font-weight: 600; color: #444; }}
  p {{ margin: 0.8em 0; }}
  code {{ background: #f2f2f7; padding: 2px 6px; border-radius: 4px; font-family: 'SF Mono', 'JetBrains Mono', monospace; font-size: 0.9em; }}
  pre {{ background: #f2f2f7; padding: 16px; border-radius: 8px; overflow-x: auto; font-size: 0.85em; }}
  pre code {{ background: none; padding: 0; }}
  blockquote {{ border-left: 3px solid #0071e3; padding-left: 16px; color: #555; font-style: italic; margin: 1em 0; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1em 0; }}
  th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
  th {{ background: #f2f2f7; font-weight: 600; }}
  a {{ color: #0071e3; }}
  ul, ol {{ padding-left: 1.5em; }}
  li {{ margin: 0.3em 0; }}
  .footer {{ text-align: center; color: #999; font-size: 9pt; margin-top: 40px; border-top: 1px solid #eee; padding-top: 10px; }}
</style>
</head>
<body>
<h1>{_html.escape(title)}</h1>
{body}
<div class="footer">Generated by Personal AI OS · {time.strftime('%B %d, %Y')}</div>
</body>
</html>"""


def _html_to_pdf(html: str, output_path: str) -> None:
    """Render HTML to PDF using weasyprint (preferred) or fpdf2 fallback."""
    try:
        from weasyprint import HTML
        HTML(string=html).write_pdf(output_path)
        return
    except ImportError:
        pass

    # Fallback: fpdf2 (simpler, no CSS support)
    try:
        from fpdf import FPDF
        from html.parser import HTMLParser

        # Strip HTML tags safely (no regex on untrusted input)
        class _TagStripper(HTMLParser):
            def __init__(self):
                super().__init__()
                self._parts: list[str] = []
            def handle_data(self, d: str):
                self._parts.append(d)
            def get_text(self) -> str:
                return "".join(self._parts)

        _stripper = _TagStripper()
        _stripper.feed(html)
        text = _stripper.get_text()
        text = text.replace('&amp;', '&').replace('&lt;', '<').replace('&gt;', '>')

        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=25)
        pdf.set_left_margin(15)
        pdf.set_right_margin(15)
        pdf.set_font("Helvetica", size=11)
        usable_w = pdf.w - pdf.l_margin - pdf.r_margin
        for line in text.split('\n'):
            stripped = line.strip()
            if not stripped:
                pdf.ln(4)
                continue
            # Break overly-long words that would exceed cell width
            try:
                pdf.multi_cell(usable_w, 6, stripped)
            except Exception:
                # Fallback: truncate line to safe length
                safe = stripped[:200] + "..." if len(stripped) > 200 else stripped
                try:
                    pdf.multi_cell(usable_w, 6, safe)
                except Exception:
                    pdf.cell(usable_w, 6, safe[:100], ln=True)
        pdf.output(output_path)
        return
    except ImportError:
        pass

    raise HTTPException(503, "No PDF library installed. Run: pip install weasyprint  or  pip install fpdf2")


@router.post("/generate")
async def generate_pdf(req: PdfGenerateRequest):
    """Generate a PDF from markdown or HTML content."""
    if not req.content.strip():
        raise HTTPException(400, "Empty content")

    if req.format == "html":
        html = req.content
    else:
        html = _markdown_to_html(req.content, req.title)

    filename = f"{hashlib.md5(req.title.encode()).hexdigest()[:8]}_{int(time.time())}.pdf"
    output_path = str(PDF_DIR / filename)
    _html_to_pdf(html, output_path)

    return {
        "filename": filename,
        "download_url": f"/pdf/file/{filename}",
        "title": req.title,
    }


@router.post("/research")
async def research_to_pdf(req: PdfResearchRequest):
    """
    Run deep research on a topic via AI, then render as a downloadable PDF.
    Uses Gemini or NVIDIA AI to generate comprehensive research content.
    """
    if not req.topic.strip():
        raise HTTPException(400, "Empty topic")

    depth_tokens = {"brief": 1500, "standard": 3000, "deep": 6000}
    max_tokens = depth_tokens.get(req.depth, 3000)

    system_prompt = f"""You are Echo, a real-time research agent. Structure your response with these headers:

[READING] — What sources and context you are examining
[THINKING] — Your reasoning about the topic (concise, step-by-step)
[PLANNING] — How you will structure the research document
[CODING] — The actual research content in markdown with:
  - A clear introduction
  - Multiple sections with ## headings
  - Key findings, data points, and analysis
  - Tables where appropriate
  - A conclusion with key takeaways
  - References section at the end
[CHECKING] — Verification of facts and completeness

Target approximately {req.pages} pages of content. Be thorough, factual, and cite sources where possible."""

    research_content = ""
    nim_base = os.getenv("NVIDIA_NIM_BASE_URL", "https://integrate.api.nvidia.com/v1")

    # ── 1. Nemotron (primary — uses NVIDIA_API_KEY) ──
    nemotron_key = os.getenv("NVIDIA_API_KEY", "")
    if nemotron_key:
        try:
            import httpx
            async with httpx.AsyncClient(timeout=180) as client:
                r = await client.post(
                    f"{nim_base}/chat/completions",
                    headers={"Authorization": f"Bearer {nemotron_key}", "Content-Type": "application/json"},
                    json={
                        "model": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
                        "messages": [
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": f"Topic: {req.topic}"},
                        ],
                        "max_tokens": max_tokens,
                        "temperature": 0.4,
                    },
                )
            if r.status_code == 200:
                data = r.json()
                research_content = data.get("choices", [{}])[0].get("message", {}).get("content", "")
                logger.info("Nemotron research OK, %d chars", len(research_content))
            else:
                logger.warning("Nemotron research %d: %s", r.status_code, r.text[:200])
        except Exception as e:
            logger.warning("Nemotron research failed: %s", e)

    # ── 2. NVIDIA Coding model (fallback) ──
    if not research_content:
        coding_key = os.getenv("NVIDIA_API_KEY_CODING", "")
        if coding_key:
            try:
                import httpx
                async with httpx.AsyncClient(timeout=120) as client:
                    r = await client.post(
                        f"{nim_base}/chat/completions",
                        headers={"Authorization": f"Bearer {coding_key}", "Content-Type": "application/json"},
                        json={
                            "model": "qwen/qwen2.5-coder-32b-instruct",
                            "messages": [
                                {"role": "system", "content": system_prompt},
                                {"role": "user", "content": f"Topic: {req.topic}"},
                            ],
                            "max_tokens": max_tokens,
                            "temperature": 0.4,
                        },
                    )
                if r.status_code == 200:
                    data = r.json()
                    research_content = data.get("choices", [{}])[0].get("message", {}).get("content", "")
            except Exception as e:
                logger.warning("NVIDIA coding research failed: %s", e)

    if not research_content:
        raise HTTPException(502, "Could not generate research content. Check NVIDIA_API_KEY.")

    # Convert to PDF
    html = _markdown_to_html(research_content, f"Research: {req.topic}")
    filename = f"research_{hashlib.md5(req.topic.encode()).hexdigest()[:8]}_{int(time.time())}.pdf"
    output_path = str(PDF_DIR / filename)
    _html_to_pdf(html, output_path)

    return {
        "filename": filename,
        "download_url": f"/pdf/file/{filename}",
        "title": req.topic,
        "depth": req.depth,
        "content_preview": research_content[:500],
    }


@router.get("/file/{filename}")
async def serve_pdf(filename: str):
    """Serve a previously generated PDF file."""
    path = (PDF_DIR / filename).resolve()
    if not path.is_relative_to(PDF_DIR.resolve()) or not path.exists():
        raise HTTPException(404, "PDF not found")
    return FileResponse(str(path), media_type="application/pdf", filename=path.name)
